# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MotionVisualize' do
pod 'Socket.IO-Client-Swift'
pod 'Pulsator'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MotionVisualize

  target 'MotionVisualizeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MotionVisualizeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
